FROM debian:stable-slim as builder

# Ethereum package config file can either be a path to a local file or a URL
ARG ETHEREUM_PACKAGE_CONFIG_FILE=https://gist.githubusercontent.com/skylenet/b6a15ce393a71a17c4b3e8f7ea614cef/raw/0c8597c5f989f3fca824dc1776aa10a897b329f5/gistfile1.txt

ARG ETHEREUM_PACKAGE=https://github.com/ethpandaops/ethereum-package
ARG ETHEREUM_PACKAGE_BRANCH="main"

# PULL all of the dependencies in here
# Known dependencies
# - prometheus
# - postgres
# - db-adminer
# - redis
ARG PROMETHEUS_PACKAGE=https://github.com/kurtosis-tech/prometheus-package
ARG PROMETHEUS_BRANCH="main"
ARG POSTGRES_PACKAGE=https://github.com/kurtosis-tech/postgres-package
ARG POSTGRES_BRANCH="main"
ARG DB_ADMINER_PACKAGE=https://github.com/bharath-123/db-adminer-package
ARG DB_ADMINER_BRANCH="main"
ARG REDIS_PACKAGE=https://github.com/kurtosis-tech/redis-package
ARG REDIS_BRANCH="main"

RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  jq \
  git \
  curl \
  make \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch ${ETHEREUM_PACKAGE_BRANCH} "${ETHEREUM_PACKAGE}" /ethereum-package && \
    git clone --depth 1 --branch ${PROMETHEUS_BRANCH} "${PROMETHEUS_PACKAGE}" /prometheus-package && \
    git clone --depth 1 --branch ${POSTGRES_BRANCH} "${POSTGRES_PACKAGE}" /postgres-package && \
    git clone --depth 1 --branch ${DB_ADMINER_BRANCH} "${DB_ADMINER_PACKAGE}" /db-adminer-package && \
    git clone --depth 1 --branch ${REDIS_BRANCH} "${REDIS_PACKAGE}" /redis-package

COPY scripts /scripts

# Download the ethereum package config file that will be used for the antithesis run
RUN ./scripts/download-package-config.sh ${ETHEREUM_PACKAGE_CONFIG_FILE} /ethereum-package/ethereum-package-config.yaml

# NOTE: making the ethereum package reference locally pulled dependencies
RUN sed -i '$ a\\nreplace:\n    github.com/kurtosis-tech/prometheus-package: ../prometheus-package\n    github.com/kurtosis-tech/postgres-package: ../postgres-package\n    github.com/bharath-123/db-adminer-package: ../db-adminer-package\n    github.com/kurtosis-tech/redis-package: ../redis-package' /ethereum-package/kurtosis.yml

FROM scratch

COPY --from=builder /ethereum-package /ethereum-package
COPY --from=builder /prometheus-package /prometheus-package
COPY --from=builder /postgres-package /postgres-package
COPY --from=builder /db-adminer-package /db-adminer-package
COPY --from=builder /redis-package /redis-package
