name: Antithesis exploration

on:
  #push:
  #  branches:
  #    - init
  workflow_dispatch:
    inputs:
      test:
        description: 'Test name'
        required: false
        default: ''
        type: string
      #ethereum_package_repo:
      #  description: 'Ethereum package version'
      #  required: true
      #  default: 'https://github.com/ethpandaops/ethereum-package'
      #  type: string
      #ethereum_package_version:
      #  description: 'Ethereum package version. Can be a branch, tag, or commit hash.'
      #  required: true
      #  default: 'main'
      #  type: string
      #ethereum_package_config_file:
      #  description: 'Ethereum package config file, either a local file or a URL'
      #  required: true
      #  default: 'tests/pectra.yaml'
      #  type: string
      config_image:
        description: 'Config image'
        required: true
        default: skylenet/ethereum-package-config:main-8f8830f
        type: string
      duration:
        description: 'Duration (exploration hours)'
        required: true
        type: number
        default: 1.0
      #description:
      #  description: 'Test run description (avoid quotes, please!)'
      #  required: true
      #  type: string
      #  default: "No description provided"
      email:
        description: 'Additional email notification recipient (separate with ;)'
        required: true
        type: string
        default: ""

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Kurtosis
      uses: ./.github/actions/kurtosis-install

    - name: Download Ethereum Package Config # TODO: move this to the config dockerfile
      run: |
        ./scripts/download-package-config.sh ${{ inputs.ethereum_package_config_file }} ethereum-package-config.yaml

    - name: Extract images for Antithesis # TODO: move this to the config dockerfile and save the output to a file
      id: extract_images
      run: |
        echo "images=$(./scripts/extract-images.sh -f semicolon ethereum-package-config.yaml)" >> $GITHUB_OUTPUT


    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: ethereum
        tenant: ethereum
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}
        config_image: ${{ inputs.config_image }} # TODO: replace this with an image that was built during the workflow run
        images: ${{ steps.extract_images.outputs.images }}
        description: "${{ github.repository }} : ${{ github.workflow }} (Run #${{ github.run_id }} : ${{ github.run_attempt }})"
        email_recipients: ${{ inputs.email }}
        test_name: ${{ inputs.test}}
        additional_parameters: |-
          custom.configuration=ethereum-package-config.yaml
          custom.duration = ${{ inputs.duration }}
