name: Antithesis exploration

on:
  #push:
  #  branches:
  #    - init
  workflow_dispatch:
    inputs:
      test:
        description: 'Test name'
        required: false
        default: 'Kurtosis Ethereum Package'
        type: string
      ethereum_package_repo:
        description: 'Ethereum package version'
        required: true
        default: 'https://github.com/ethpandaops/ethereum-package'
        type: string
      ethereum_package_version:
        description: 'Ethereum package version. Can be a branch, tag, or commit hash.'
        required: true
        default: 'main'
        type: string
      ethereum_package_config_file:
        description: 'Ethereum package config file URL'
        required: true
        default: 'https://raw.githubusercontent.com/ethpandaops/ethereum-package/refs/heads/main/.github/tests/mix.yaml'
        type: string
      duration:
        description: 'Duration (exploration hours)'
        required: true
        type: number
        default: 1.0
      email:
        description: 'Additional email notification recipient (separate with ;)'
        required: true
        type: string
        default: ""

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Kurtosis
      uses: ./.github/actions/kurtosis-install

    - name: Extract images for Antithesis
      id: extract_images
      env:
        ETHEREUM_PACKAGE_REPO: ${{ inputs.ethereum_package_repo }}
        ETHEREUM_PACKAGE_VERSION: ${{ inputs.ethereum_package_version }}
        CONFIG_FILE: ${{ inputs.ethereum_package_config_file }}
      run: |
        echo "images=$(make antithesis-images-list)" >> $GITHUB_OUTPUT

    - name: Build config image
      id: build_config_image
      env:
        ETHEREUM_PACKAGE_REPO: ${{ inputs.ethereum_package_repo }}
        ETHEREUM_PACKAGE_VERSION: ${{ inputs.ethereum_package_version }}
        CONFIG_FILE: ${{ inputs.ethereum_package_config_file }}
        CONFIG_IMAGE_NAME: ghcr.io/ethpandaops/ethereum-package-config
        CONFIG_IMAGE_TAG: ${{ github.run_id }}-${{ github.run_attempt }}
      run: |
        make config-image
        echo "config_image=ghcr.io/ethpandaops/ethereum-package-config:${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

    - name: Push config image
      run: |
        docker push ${{ steps.build_config_image.outputs.config_image }}

    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: ethereum
        tenant: ethereum
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}
        config_image: ${{ steps.build_config_image.outputs.config_image }}
        images: ${{ steps.extract_images.outputs.images }}
        description: "${{ github.repository }} : ${{ github.workflow }} (Run #${{ github.run_id }} : ${{ github.run_attempt }})"
        email_recipients: ${{ inputs.email }}
        test_name: ${{ inputs.test_name }}
        additional_parameters: |-
          custom.configuration=ethereum-package-config.yaml
          custom.duration = ${{ inputs.duration }}
